/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Thread t = new MyThread();
        t.start();
        System.out.println("Current Thread is:"+Thread.currentThread().getName());
    }

    static class MyThread extends Thread {

        @Override
        public void run(){
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            System.out.println("Current Thread is:"+Thread.currentThread().getName());
        }

    }
}
